### PR TITLE
If the image can't be loaded display the default cover

### LINKED ISSUE #36: [Title-Card] If the image can't be loaded display the default cover
> This is an "improvement" to the title-card implemented in issue #9.

Currently, if you want to display the default cover rather than an image you use the following code.

```html
<div class="lf-title-card missing">
    <i class="lf-play-btn fa fa-play-circle-o" aria-hidden="true"></i>
    <div class="lf-title">Missing Movie Info</div>
    <i class="lf-missing-icon fa fa-exclamation-circle" aria-hidden="true"></i>
</div>
```

but what if you know an image URL, but the image doesn't load? The result looks like this

image

My suggestion is rather than letting the user decide when to display an actual cover and when to display the default cover let the component figure that out. Whenever no cover is defined or the image doesn't load show a default cover.

However, the solution looks like keep user required definition as simple as possible. For more info on that take a look at issue #35. 

### Links that may help
[Different solutions](https://stackoverflow.com/questions/980855/inputting-a-default-image-in-case-the-src-attribute-of-an-html-img-is-not-vali)

### PR DESCRIPTION
**Pull request by SaiKai**
fixes #36

### CODE REVIEW

**Comment by KenavR** [comment]
Thanks for contributing to the project. Sadly your Pull Request doesn't really do what is asked. If you read the answer on StackOverflow the provided `<object>` node is used when the actual `` inside the `<object>`  doesn't resolve to an image. In your solution, the inside of the object never resolves to an image (since there is no `` tag in it) and therefore displays the provided image in the object's data attribute. As stated in the SO answer the URL in the data attribute holds the fallback image.

Additionally, as stated in issue #35 it would be preferable if the user doesn't have to write the entire fallback solution and it rather gets injected by some Javascript. If you are not comfortable with Javascript, let me know and I will accept an updated PR (with the small problem above) and let someone else work on the Javascript portion.

**Comment by SaiKai** [comment]
I don't think you understand what the object tag does. It embeds a file into the document. If the embedded file for instance can not be reached, it will display its alternate text (which is everything between the `<object></object>` tag). In this case, if the `image_src` is left blank (or doesn't resolve to an image), it will display the alternate content (which is the missing icon).
You can checkout my changes and see it working for yourself.

Regarding issue #35, i only did the changes that were needed to achieve the required effect for #36, as you opened a separate issue for the javascript part. If this wasn't intended, you can close this pull request.

**Comment by KenavR** [comment]
Sorry my mistake, I misread the SO answer, I thought it was the other way around. 

> You can checkout my changes and see it working for yourself.
That's what I did and it didn't work. Instead of looking more into it, I wrote the response. It does work in Firefox and IE(dge) but not in Chrome. The element is not at the position it should be.

image

You are right the JS portion of issue #36 was just a suggestion and no hard requirement, I will accept the PR after it works in Chrome or if you have no interest in looking into the Chrome "bug" I will accept it now and move the bug fix into a new issue.

**Comment by SaiKai** [comment]
Sorry, i didn't test it with other browsers. I will implement a different method of setting a default cover.

**Comment by KenavR** [comment]
With some small changes, it works well. If you run the server the browser can't find the default image (at least here) because the root of the static resources is the ["front-end"](https://github.com/DevvitIO/Lanflix/blob/master/back-end/server.js#L11) directory. If I change it to "component-playground/default.png" it works. 

Anyhow, since the default image is part of the component and not necessary the playground the image should be stored somewhere accessible from the main application (the playground won't be deployed to production). I suggest moving the image and the "title-card.css" file into a directory named "title-card" and fixing the links.

**Pull request merged**
