### PR TITLE
Added /series endpoint

### PR DESCRIPTION
**Pull request by ozgunbal**
Implemented for #23 

Happy Hacktoberfest!

### CODE REVIEW

**Comment by KenavR** [comment]
Thank you for your contribution. I will look into the PR during the day and merge it. Are you German by any chance? (I am asking because the singular of series in English is also series, but that's no big deal)

**Comment by ozgunbal** [comment]
I should google it first :) I intuitively set for 'serie', my mistake. Other than that, i'm new on back-end dev, but i  would like to help for other endpoints and stuff. I also open to all kinds of feedbacks.

**Comment by KenavR** [comment]
I am happy you want to help, I am currently just focused on managing the project, but if you need anything to contribute or a dependency implemented let me know. The PR looks great, I have just one suggestion. The [http status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) have specific meanings and 404 means that the client has requested a resource that can not be found (client-side error), but here, the endpoint is already reached and the error is thrown while querying the database. It would be better to return a server-side error code (5xx) in this case I would just use the generic 500.

If you want to change it, I am going to let the PR open for a couple of hours otherwise, I will just merch it and update it afterwards. Thanks

**Comment by KenavR** [comment]
Amazing thanks.

**Pull request merged**
